import prismadb from "@/lib/prismadb";
import { NextResponse } from "next/server";

export const GET = async () => {
  try {
    const pets = [
      {
        title: "Tulip",
        tags: {
          gender: "Female",
          "weight-category": "L",
          species: "Dog",
          breed: "Australian Cattle Dog",
          color: "White",
          location: "12",
          site: "Mission Adoption Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/50906698/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2023/09/14183b0f-bb82-417f-aa9b-f8a391fe1e7a.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: true,
      },
      {
        title: "Kettle Corn",
        tags: {
          gender: "Male",
          "weight-category": "L",
          species: "Dog",
          breed: "Doberman Pinscher",
          color: "Black",
          location: "12",
          site: "Mission Adoption Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/51976495/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2023/11/2a0ffbd4-71cc-485c-a39c-39c926d32a79.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: true,
      },
      {
        title: "Yoda",
        tags: {
          gender: "Male",
          "weight-category": "S",
          species: "Dog",
          breed: "Chihuahua",
          color: "Grey",
          location: "12",
          site: "Mission Adoption Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/51987507/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/02/a2dbf01b-f325-4257-b62b-eafb75f168c4.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: true,
      },
      {
        title: "Xochi",
        tags: {
          gender: "Female",
          "weight-category": "M",
          species: "Dog",
          breed: "Basenji",
          color: "Red",
          location: "12",
          site: "Mission Adoption Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/50506098/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/01/e846d8ef-aebc-4720-9632-85f197ecaa44.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: true,
      },
      {
        title: "Nala",
        tags: {
          gender: "Female",
          "weight-category": "L",
          species: "Dog",
          breed: "Cur",
          color: "Tan",
          location: "Foster Home",
          site: "Foster Program",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/52132231/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/01/972d2bf8-a6eb-49d1-a7fa-268ebd174e11.jpg",
        bonded: false,
        location: "In a Foster Home",
        foster_to_adopt: true,
      },
      {
        title: "Lucy",
        tags: {
          gender: "Female",
          "weight-category": "L",
          species: "Dog",
          breed: "Retriever",
          color: "Black",
          location: "12",
          site: "Mission Adoption Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/54872647/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/01/15ec52eb-9924-4df9-a4f8-e5840fd3ceca.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: true,
      },
      {
        title: "Roscoe",
        tags: {
          gender: "Male",
          "weight-category": "S",
          species: "Dog",
          breed: "Chihuahua",
          color: "Brown",
          location: "12",
          site: "Mission Adoption Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/55082986/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/02/cff155f9-d548-4c0a-ac2c-ac5072cfa6c1.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: false,
      },
      {
        title: "Kaya",
        tags: {
          gender: "Female",
          "weight-category": "M",
          species: "Dog",
          breed: "Siberian Husky",
          color: "Grey",
          location: "12",
          site: "Mission Adoption Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/55109611/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/01/80a6290b-36f5-474a-aa3c-f25aa74c7b94.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: true,
      },
      {
        title: "Jackson",
        tags: {
          gender: "Male",
          "weight-category": "M",
          species: "Dog",
          breed: "Carolina Dog",
          color: "White",
          location: "12",
          site: "Mission Adoption Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/54962374/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/01/6db2a34b-94aa-4fe5-8081-984f1eef6f14.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: true,
      },
      {
        title: "Piglet",
        tags: {
          gender: "Male",
          "weight-category": "S",
          species: "Dog",
          breed: "Chihuahua",
          color: "Brown",
          location: "12",
          site: "Mission Adoption Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/55133921/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/02/36635c62-6b2f-4770-9300-763353e75bb3.jpg",
        bonded: true,
        location: false,
        foster_to_adopt: true,
      },
      {
        title: "Roo",
        tags: {
          gender: "Male",
          "weight-category": "S",
          species: "Dog",
          breed: "Chihuahua",
          color: "Tan",
          location: "12",
          site: "Mission Adoption Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/55133927/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/02/9a668331-10fc-492b-8106-38ab8fe96fc3.jpg",
        bonded: true,
        location: false,
        foster_to_adopt: true,
      },
      {
        title: "Bernardo",
        tags: {
          gender: "Male",
          "weight-category": "L",
          species: "Dog",
          breed: "Spinone Italiano",
          color: "Brown",
          location: "12",
          site: "Mission Adoption Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/55039742/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/02/f1a3738d-0148-4e26-b870-ded2b5548b56.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: false,
      },
      {
        title: "Elsa",
        tags: {
          gender: "Female",
          "weight-category": "S",
          species: "Dog",
          breed: "Shepherd",
          color: "Black",
          location: "12",
          site: "Mission Adoption Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/55230256/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/02/afbc0984-da5f-4b65-b0f9-77f41023b549.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: false,
      },
      {
        title: "Elena",
        tags: {
          gender: "Female",
          "weight-category": "S",
          species: "Dog",
          breed: "Shepherd",
          color: "Black",
          location: "2416",
          site: "Leanne Roberts Animal Care Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/55230239/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/02/5645f8ec-a7a0-4246-bc9a-5a2a74e5d7d7.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: false,
      },
      {
        title: "Tammy",
        tags: {
          gender: "Female",
          "weight-category": "S",
          species: "Dog",
          breed: "Chihuahua",
          color: "Brown",
          location: "2425",
          site: "Leanne Roberts Animal Care Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/54092471/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2023/09/37ea64bc-54cd-44af-ab95-839949d08f3c.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: false,
      },
      {
        title: "Preston",
        tags: {
          gender: "Male",
          "weight-category": "XS",
          species: "Dog",
          breed: "Chihuahua",
          color: "Beige",
          location: "22",
          site: "Shelter Annex",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/55109732/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/02/6144ae82-8387-45f0-ad00-9e5b56323433.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: false,
      },
      {
        title: "Goofy",
        tags: {
          gender: "Male",
          "weight-category": "L",
          species: "Dog",
          breed: "Australian Shepherd",
          color: "Brown",
          location: "12",
          site: "Mission Adoption Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/55238916/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/02/8034035d-505f-437c-828d-6e91a1c7f62b.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: false,
      },
      {
        title: "Darla",
        tags: {
          gender: "Female",
          "weight-category": "M",
          species: "Dog",
          breed: "Terrier",
          color: "Black",
          location: "12",
          site: "Mission Adoption Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/54962351/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/02/63b50c7e-d542-4a41-bda4-0e6ca012d922.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: false,
      },
      {
        title: "Lady",
        tags: {
          gender: "Female",
          "weight-category": "M",
          species: "Dog",
          breed: "Terrier",
          color: "Black",
          location: "12",
          site: "Mission Adoption Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/55256252/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/02/097c434b-e6b0-42ab-b243-9c4fd444cfa9.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: false,
      },
      {
        title: "Bambi",
        tags: {
          gender: "Female",
          "weight-category": "S",
          species: "Dog",
          breed: "Australian Cattle Dog",
          color: "Red",
          location: "12",
          site: "Mission Adoption Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/55256550/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/02/e02e9f62-ff95-47d7-b3fa-d190625fd94b.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: false,
      },
      {
        title: "Bogo",
        tags: {
          gender: "Male",
          "weight-category": "XS",
          species: "Dog",
          breed: "Terrier",
          color: "Brown",
          location: "2416",
          site: "Leanne Roberts Animal Care Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/55271045/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/02/f91b555f-b731-4a9b-aa79-3dfc348ccad1.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: false,
      },
      {
        title: "Charlotte",
        tags: {
          gender: "Female",
          "weight-category": "XS",
          species: "Dog",
          breed: "Terrier",
          color: "Brown",
          location: "2416",
          site: "Leanne Roberts Animal Care Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/55270972/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/02/f9af19fb-7de4-43b9-9e11-60f9e8789b0e.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: false,
      },
      {
        title: "Flash",
        tags: {
          gender: "Male",
          "weight-category": "XS",
          species: "Dog",
          breed: "Terrier",
          color: "Brown",
          location: "2416",
          site: "Leanne Roberts Animal Care Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/55271057/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/02/2d0f43a2-a974-40c2-860e-49f22156bced-1.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: false,
      },
      {
        title: "Priscilla",
        tags: {
          gender: "Female",
          "weight-category": "XS",
          species: "Dog",
          breed: "Terrier",
          color: "White",
          location: "2416",
          site: "Leanne Roberts Animal Care Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/55271050/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/02/5bdb8508-361f-4a28-bd24-9e6e05806967.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: false,
      },
      {
        title: "Wilde",
        tags: {
          gender: "Male",
          "weight-category": "XS",
          species: "Dog",
          breed: "Terrier",
          color: "Brown",
          location: "2416",
          site: "Leanne Roberts Animal Care Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/55271040/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/02/d943268d-9895-4ea3-8100-5da75a970e77.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: false,
      },
      {
        title: "Hiro",
        tags: {
          gender: "Male",
          "weight-category": "S",
          species: "Dog",
          breed: "Alaskan Husky",
          color: "Grey",
          location: "12",
          site: "Mission Adoption Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/55270991/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/02/18662ae0-f5b3-4d32-a568-dba65aa6de00.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: false,
      },
      {
        title: "Percy",
        tags: {
          gender: "Male",
          "weight-category": "S",
          species: "Dog",
          breed: "Terrier",
          color: "White",
          location: "2425",
          site: "Leanne Roberts Animal Care Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/55387728/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/02/689cae0b-4ab7-4bf8-92b9-2ccb0cd3c672.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: false,
      },
      {
        title: "Rita",
        tags: {
          gender: "Female",
          "weight-category": "M",
          species: "Dog",
          breed: "Shepherd",
          color: "Tan",
          location: "2431",
          site: "Leanne Roberts Animal Care Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/55387698/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/02/aafb5446-20f6-44ea-b96a-4d5b41d5e751.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: false,
      },
      {
        title: "Trusty",
        tags: {
          gender: "Female",
          "weight-category": "S",
          species: "Dog",
          breed: "Chihuahua",
          color: "Black",
          location: "2425",
          site: "Leanne Roberts Animal Care Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/55387711/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/02/8e7f592c-3074-4a67-81a3-920a3d362457.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: false,
      },
      {
        title: "Amelia",
        tags: {
          gender: "Female",
          "weight-category": "S",
          species: "Dog",
          breed: "Chinese Shar-Pei",
          color: "Apricot",
          location: "2425",
          site: "Leanne Roberts Animal Care Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/55387682/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/02/3538c9a0-6902-41e8-978e-bcaeb22fd98d.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: false,
      },
      {
        title: "Slinky",
        tags: {
          gender: "Male",
          "weight-category": "XS",
          species: "Dog",
          breed: "Terrier",
          color: "Brown",
          location: "2416",
          site: "Leanne Roberts Animal Care Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/55247671/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/02/483da257-7ae7-4749-967b-f6af3aaa7413.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: false,
      },
      {
        title: "Judy",
        tags: {
          gender: "Female",
          "weight-category": "M",
          species: "Dog",
          breed: "Siberian Husky",
          color: "Grey",
          location: "12",
          site: "Mission Adoption Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/55270164/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/02/45d78f7b-c415-4d7d-9942-465ee85bd27c.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: false,
      },
      {
        title: "Penny",
        tags: {
          gender: "Female",
          "weight-category": "M",
          species: "Dog",
          breed: "Terrier",
          color: "Brown",
          location: "2431",
          site: "Leanne Roberts Animal Care Center",
        },
        permalink: "https://www.sfspca.org/sfspca-adoption/55173445/",
        thumb:
          "https://www.sfspca.org/wp-content/uploads/2024/01/379ddd7e-60b5-4788-9dfd-b82c5cd40502.jpg",
        bonded: false,
        location: false,
        foster_to_adopt: false,
      },
    ];

    return NextResponse.json({ pets }, { status: 200 });
  } catch (error: any) {
    return NextResponse.json({ message: error.message }, { status: 500 });
  }
};
